name: "Infra: Feature Testing: Init env"

on:
  workflow_dispatch:

  pull_request:
    types: ['labeled']

permissions:
  contents: read

jobs:
  initiate_env:
    if: ${{ github.event.label.name == 'status/feature_testing' || github.event.label.name == 'status/feature_testing_public' }}
    runs-on: ubuntu-latest
    steps:
      - name: Call Build Workflow
        id: build
        uses: ./.github/workflows/build.yml
        with:
          head_sha: ${{ github.event.pull_request.head.sha }}
          pull_request_number: ${{ github.event.pull_request.number }}
          
      - name: Call Push Workflow
        uses: ./.github/workflows/push.yml
        with:
          version: ${{ steps.build.outputs.version }}
          tag: ${{ steps.build.outputs.tag }}

  make-branch-env:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: clone
        run: |
          git clone https://infra-tech:${{ secrets.INFRA_USER_ACCESS_TOKEN }}@github.com/kafbat/kafka-ui-infra.git --branch envs
      - name: create deployment
        run: |
          cd kafka-ui-infra/aws-infrastructure4eks/argocd/scripts
          echo "Branch:${{ needs.build.outputs.tag }}"
          ./kafka-ui-deployment-from-branch.sh ${{ needs.build.outputs.tag }} ${{ github.event.label.name }} ${{ secrets.FEATURE_TESTING_UI_PASSWORD }}
          git config --global user.email "infra@kafbat.io"
          git config --global user.name "infra-tech"
          git add ../kafka-ui-from-branch/
          git commit -m "added env:${{ needs.build.outputs.deploy }}" && git push || true

      - name: update status check for private deployment
        if: ${{ github.event.label.name == 'status/feature_testing' }}
        uses: Sibz/github-status-action@v1.1.6
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "Click Details button to open custom deployment page"
          state: "success"
          sha: ${{ github.event.pull_request.head.sha  || github.sha }}
          target_url: "http://${{ needs.build.outputs.tag }}.internal.ui.kafbat.dev"

      - name: update status check for public deployment
        if: ${{ github.event.label.name == 'status/feature_testing_public' }}
        uses: Sibz/github-status-action@v1.1.6
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "Click Details button to open custom deployment page"
          state: "success"
          sha: ${{ github.event.pull_request.head.sha  || github.sha }}
          target_url: "http://${{ needs.build.outputs.tag }}.internal.ui.kafbat.dev"
